version: '3'

services:

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ../data/realms/:/opt/keycloak/data/import/
    command: ["start-dev"]

  mysql-inventory:
    image: mysql:8.3.0
    container_name: mysql-inventory
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: inventory_service
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ~/data/mysql-inventory:/var/lib/mysql

  mysql-order:
    image: mysql:8.3.0
    container_name: mysql-order
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: order_service
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ~/data/mysql-order:/var/lib/mysql

  mongo-product:
    image: mongo:4.4.14-rc0-focal
    container_name: mongo-product
    ports:
      - "27017:27017"
    volumes:
      - ~/data/mongo-data:/data/db
